-- 1. Create a table for contact form leads
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL
);

-- 2. Create a table for trainers
CREATE TABLE IF NOT EXISTS trainers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  specialty TEXT NOT NULL,
  image_url TEXT NOT NULL,
  social_links JSONB DEFAULT '{}'::jsonb
);

-- 3. Create a table for pricing plans
CREATE TABLE IF NOT EXISTS pricing_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  price DECIMAL NOT NULL,
  description TEXT,
  features TEXT[] DEFAULT '{}',
  is_popular BOOLEAN DEFAULT false
);

-- 4. Create a table for gym services
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,
  icon_name TEXT -- Lucide icon name string
);

-- Enable Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE trainers ENABLE ROW LEVEL SECURITY;
ALTER TABLE pricing_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Leads: Anyone can insert, only auth can read
CREATE POLICY "Enable insert for everyone" ON leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for authenticated users only" ON leads FOR SELECT USING (auth.role() = 'authenticated');

-- Trainers, Plans, Services: Everyone can read, only auth can modify
CREATE POLICY "Public read for trainers" ON trainers FOR SELECT USING (true);
CREATE POLICY "Public read for pricing_plans" ON pricing_plans FOR SELECT USING (true);
CREATE POLICY "Public read for services" ON services FOR SELECT USING (true);
